#!/usr/bin/env python3
"""Generate double-clickable launchers for this project.

Run once per machine: python src/install_launchers.py

Writes two launchers into launch/ — one for the export tool (reads
config.json, so run from the repo) and one for the slideshow server —
in the format your OS can double-click:

- Linux:   X Export.desktop / X Slideshow.desktop (+ .sh helpers)
- macOS:   X Export.command / X Slideshow.command
- Windows: X Export.bat / X Slideshow.bat

Re-run after moving the repository: the Linux files embed absolute paths.
"""

import os
import pathlib
import sys
import typing

REPO_ROOT = pathlib.Path(__file__).parent.parent.resolve()
"""The repository root (parent of src/)."""

LAUNCH_DIR = REPO_ROOT / "launch"
"""Where the launchers are written."""

EXPORT_COMMENT = "Fetch liked or bookmarked photos from X and download them"
SLIDESHOW_COMMENT = "Host the exported photos as a slideshow in your browser"

EXPORT_SH = """#!/bin/bash
# Generated by install_launchers.py — double-click to run the X export tool.
# config.json is read from the repo root, so cd there first.
cd "$(dirname "$0")/.." || exit 1
.venv/bin/python src/main.py
echo
read -n 1 -s -r -p "Press any key to close..."
echo
"""

SLIDESHOW_SH = """#!/bin/bash
# Generated by install_launchers.py — start the slideshow server and open it
# in your browser. Close this window (or press Ctrl+C) to stop the server.
cd "$(dirname "$0")/.." || exit 1
.venv/bin/python src/slideshow.py --open-browser
"""

EXPORT_BAT = """@echo off
rem Generated by install_launchers.py - double-click to run the X export tool.
rem config.json is read from the repo root, so cd there first.
cd /d "%~dp0\\.." || exit /b 1
.venv\\Scripts\\python.exe src\\main.py
echo.
pause
"""

SLIDESHOW_BAT = """@echo off
rem Generated by install_launchers.py - start the slideshow server and open
rem it in your browser. Close this window to stop the server.
cd /d "%~dp0\\.." || exit /b 1
.venv\\Scripts\\python.exe src\\slideshow.py --open-browser
"""

DESKTOP_ENTRY = """[Desktop Entry]
Type=Application
Version=1.0
Name={name}
Comment={comment}
Exec={exec_path}
Terminal=true
Categories=Utility;
"""
"""A freedesktop entry. Terminal=true opens a terminal window for output."""


def posix_scripts() -> typing.Dict[str, str]:
    """Shell wrappers shared by the Linux and macOS launchers.

    They locate the repo via their own path, so they keep working if the
    repository is moved.
    """
    return {"export.sh": EXPORT_SH, "slideshow.sh": SLIDESHOW_SH}


def linux_launchers(repo: pathlib.Path) -> typing.Dict[str, str]:
    """Shell wrappers plus .desktop entries pointing at them."""
    def entry(name: str, comment: str, script: str) -> str:
        exec_path = str(repo / "launch" / script).replace("\\", "\\\\").replace('"', '\\"')
        return DESKTOP_ENTRY.format(name=name, comment=comment, exec_path=f'"{exec_path}"')

    return {
        **posix_scripts(),
        "X Export.desktop": entry("X Export", EXPORT_COMMENT, "export.sh"),
        "X Slideshow.desktop": entry("X Slideshow", SLIDESHOW_COMMENT, "slideshow.sh"),
    }


def mac_launchers(repo: pathlib.Path) -> typing.Dict[str, str]:
    """macOS .command files: shell scripts Finder runs in Terminal."""
    scripts = posix_scripts()
    return {
        "X Export.command": scripts["export.sh"],
        "X Slideshow.command": scripts["slideshow.sh"],
    }


def windows_launchers(repo: pathlib.Path) -> typing.Dict[str, str]:
    """Windows batch files."""
    return {
        "X Export.bat": EXPORT_BAT,
        "X Slideshow.bat": SLIDESHOW_BAT,
    }


LAUNCHERS = {
    "linux": linux_launchers,
    "darwin": mac_launchers,
    "win32": windows_launchers,
}
"""Launcher generators per sys.platform value."""


def install(launch_dir: pathlib.Path, platform: str) -> typing.List[pathlib.Path]:
    """Write the platform's launchers into launch_dir.

    Marks them executable on POSIX platforms. Overwrites existing files,
    so it is safe to re-run.

    :param launch_dir: The directory to write the launchers into.
    :param platform: The sys.platform value to generate for.
    :return: The written file paths.
    :raises ValueError: If the platform is not supported.
    """
    if platform not in LAUNCHERS:
        raise ValueError(
            f"Unsupported platform: {platform!r} (expected one of: {', '.join(LAUNCHERS)})"
        )

    repo = launch_dir.parent
    launch_dir.mkdir(parents=True, exist_ok=True)
    written = []
    for name, content in LAUNCHERS[platform](repo).items():
        path = launch_dir / name
        path.write_text(content, encoding="utf-8", newline="\n")
        if platform != "win32":
            path.chmod(0o755)
        written.append(path)
    return written


def main() -> None:
    """Entry point."""
    written = install(LAUNCH_DIR, sys.platform)
    print(f"Created {len(written)} launcher(s) in {LAUNCH_DIR}:")
    for path in written:
        print(f"  {path.name}")
    print("\nDouble-click one to run it. Re-run this installer if you move the repository.")


if __name__ == "__main__":
    main()
